### ISSUE TITLE
Clearly delineate zim configuration additions

### ISSUE THREAD

**Issue by Eriner** [zimfw/install#4] opened 2020-01-11 17:08 UTC
Would be nice to have a upper and lower bounds comment block that delineates what is added to configuration files.

Currently, if you have this in your `.zshrc`:
```
alias dosomestuff='echo 123'
```

And then run the installer, you'll end up with this:
```
#
# User configuration sourced by interactive shells
#

...omitted for brevity...

bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
alias dosomestuff='echo 123'
```

Hard to tell where the additions end. Adding a header and a footer similar to the following (and a trailing newline) would help:
```
# Start zimfw configuration

# End zimfw configuration
```

**Comment by ericbn** [comment] 2020-01-17 01:39
Cannot reproduce. When I do:

```
% export ZDOTDIR=${PWD}
% rm -rf .z*
% print 'print .zshrc' > .zshrc
% curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
```
I get:
```
% tail .zshrc
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

print .zshrc
```

EDIT: Which makes sense, because the template already has a newline at the end [here](https://github.com/zimfw/install/blob/5243b4f13a0aff62af3109f10828acbb42e1cc9e/install.zsh#L278), plus we do print it [here](https://github.com/zimfw/install/blob/5243b4f13a0aff62af3109f10828acbb42e1cc9e/install.zsh#L284) which will add another newline.

**Comment by ericbn** [comment] 2020-01-17 02:03
If issue is not also about the blank line after the template addition, but specifically only about the delineates, then it's fixed in the latest commit.

**Closed as completed** 2020-01-17 02:03 UTC
